# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-10 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=6)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('organisation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=60)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('fee_normal', models.BooleanField(default=False)),
                ('fee_student', models.BooleanField(default=False)),
                ('fee_one_day', models.BooleanField(default=False)),
            ],
        ),
    ]
